[package]
name = "elektron_ngspice"
version = "0.1.0"
edition = "2021"
description = "ngspice bindings for elektron"
license = "MIT OR Apache-2.0"

[lib]
name = "elektron_ngspice"

[dependencies]
libloading = "0.7.3"

[build-dependencies]
bindgen = "0.60.1"
